### ISSUE TITLE
Nested begin/end indexing no longer supported

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/AbstractPPL.jl#23]
Back in the day, doing something like `x[1][end]` was possible, but it no longer is:

```julia
julia> AbstractPPL.vinds(:(x[1][end]))
:((((lastindex)(var"##S#319"),),))
```

which references an undefined variable. This is because of the `Base.replace_ref_begin_end!`:

```julia
julia> Base.replace_ref_begin_end!(:(x[1][end]))
:(let var"##S#320" = x[1]
      var"##S#320"[(lastindex)(var"##S#320")]
  end)
```

which is then further altered afterwards in

https://github.com/TuringLang/AbstractPPL.jl/blob/34fc3e1ba12057993aa64fb850d392fa3b06a354/src/varname.jl#L357-L364

resulting in the incorrect generated code.

Is this intended?

**Comment by phipsgabler** [comment]
Not intented, no.  Very good point, it seems like this just didn't get properly tested.  I guess it needs to be rewritten to

```
:(let var"##S#320" = x[1]
      VarName{:x}(((lastindex(var"##S#320"),),))
  end)
```

right?

**Comment by torfjelde** [comment]
It needs to rewritten to

```julia
:(let var"##S#320" = x[1]
      VarName{:x}(((1, ), (lastindex(var"##S#320"),),))
  end)
```

Essentially doing what `Base.replace_ref_begin_end!` does but we need to capture the full indexing being used.

**Comment by torfjelde** [comment]
Seems like we'd have to re-implement `Base.replace_ref_begin_end!`? It seems a bit complicated though

https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/base/views.jl#L17-L75

**Comment by phipsgabler** [comment]
I think it should work now.  But there's even more gensyms in the doctests, which it isn't gonna like.
