### ISSUE TITLE
Minor performance issue with `Setfield` 

### ISSUE THREAD

**Issue by yebai** [TuringLang/AbstractPPL.jl#28]
See https://github.com/TuringLang/AbstractPPL.jl/pull/26#issuecomment-900167979

**Comment by phipsgabler** [comment]
The reason is the default `hash` method for lenses, see https://github.com/jw3126/Setfield.jl/issues/161.

**Comment by phipsgabler** [comment]
@torfjelde could you check the benchmarks again with Setfield 0.8.0, as soon as it's out?

**Comment by torfjelde** [comment]
![image](https://user-images.githubusercontent.com/11074788/140616874-025817f2-c497-4529-a5a4-d9d541b90cac.png)

It's indeed fixed:)
