### ISSUE TITLE
Feature requests and use cases

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/AbstractPPL.jl#3]
Here are some features and use cases that @cscherrer brought up on Slack.

- Inlining data in a model
- But not forcing that - data can also be external
- Online modeling, e.g. Kalman filtering
- Pyro-style approach, passing `model` and `guide`
- Refactoring, e.g. change to non-centered parameterization
- Composability - models as distributions, etc
- Easily switch between prior, posterior, likelihood
- Posterior predictive checks

**Comment by femtomc** [comment]
Tracking this thread too :) Will add some comments later.

**Comment by cscherrer** [comment]
I'd forgotten we had talked about inlining. I guess you may all have seen it by now, but I presented some progress on that idea here:
https://informativeprior.com/blog/2021/01-25-symbolic-simplification/
