### ISSUE TITLE
Suggested Features

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/AbstractPPL.jl#34]
I'm leaving these here as examples of things I wanted while building ParetoSmooth.jl:
1. Some kind of `AbstractModel` type that I can dispatch on.
2. A `log_pdf` function.
3. A way to instantiate a model on some counterfactual dataset -- either by calling some `AbstractModel` object on a dataset or by having `condition/decondition` functions.

**Comment by devmotion** [comment]
1. There exists `AbstractPPL.AbstractProbabilistivProgram <: AbstractMCMC.AbstractModel`. `DynamicPPL.Model` (ie Turing models) are a subtype of it.
2. There exists `AbstractPPL.logdensity` and `loglikelihood`, `logprior`, and `logprior` for Turing models.
3. There exists `AbstractPPL.condition` and `AbstractPPL.decondition`, and it's also implemented for Turing models (with some restriction for backward compatibility, as explained in the docstring).

**Comment by phipsgabler** [comment]
Yeah, this is basically all described in the [interface draft](https://github.com/TuringLang/AbstractPPL.jl/blob/main/interface.md#tldr).  (The abstract supertype is not, I think, but already exists.)

Note though that we are still in the process of refining this.  `condition`/`decondition` work in DynamicPPL, but only with named tuples.  As described in the draft, there needs to come some more flexible syntax.  And for counterfactuals -- I'm not sure what exactly you mean, but I mention the possibility of having a do-operator in the prob-syntax at some place below.

Feel free to reach out to me with question, I'm always keen on refining my understanding of what downstream packages need from the interface (are you in the Turing Slack?)
