### ISSUE TITLE
Use `repr` for pretty printing indices

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/AbstractPPL.jl#50]
Currently, except for the special case `:`, `string` is used to print indices. I think we should use `repr` instead, because:

```julia
julia> @varname(x[:a])
x[a]

julia> string(:a)
"a"

julia> repr(:a)
":a"
```

I think `x[a]` is a misrepresentation.  

From the docs: 

> Note that repr(x) is usually similar to how the value of x would be entered in Julia.

**Comment by torfjelde** [comment]
Haha, I just noticed this yesterday too when noting the bug in the PR and meant to make a PR today replacing it with `repr` :sweat:
