### ISSUE TITLE
Tag a new version compatible with Setfield@1

### ISSUE THREAD

**Issue by skleinbo** [TuringLang/AbstractPPL.jl#74]
Would that be possible? E.g. `Makie@0.19` has dropped support for `Setfield<1` which makes coexistence of both recent `Makie` and `Turing` versions impossible.

**Comment by torfjelde** [comment]
Thanks for pointing this out! Trigger a release now. Once that hits, we'll bump the dep in DPPL and it should be fine. Should hopefully all be done today.

**Comment by yebai** [comment]
Fixed now
